### ISSUE TITLE
Create the sign up page

### ISSUE THREAD

**Issue by tbm5k** [mazarynxyz/mazaryn-frontend#10]
Convert the [sign-up.html](https://github.com/mazarynxyz/mazaryn-frontend/blob/main/src/sign-up.html) file into a react conponent

**Comment by Godwindaniel10** [comment]
Hi @tbm5k ,
i do like to work on this issue

**Comment by tbm5k** [comment]
Hi @Godwindaniel10 , I have assigned the issue to you, go ahead and work on it

**Comment by tbm5k** [comment]
@Godwindaniel10 have you seen the prototype on figma?

**Comment by Godwindaniel10** [comment]
@tbm5k ok on it...
yeah I have seen the prototype
