### ISSUE TITLE
Routing bug 🐞

### ISSUE THREAD

**Issue by tbm5k** [mazarynxyz/mazaryn-frontend#13]
When you reroute to let's say 
```http://localhost:3000/profile``` 
after logging in, you are redirected to the sign-in page which is not the expected behavior. I thought this could probably be that the logged-in status gets set to false every time the app component runs, so I took the variable out of the App component scope but the problem still prevails. 

*From*
```js
function App() {
  ....
  //state of the user stored for the session
  const [userDetails, setUserDetails] = useState({
    email: '',
    loggedIn: false
  });
  ...
```
*To*
```js
let loggedin = false

function App() {
  ...
  //state of the user stored for the session
  const [userDetails, setUserDetails] = useState({
    email: ''
  });
  ...
```

**Comment by tbm5k** [comment]
Done some research and the problem is brought about when React **re-renders** the App component when a change is detected. Using the `context API` to store the session could possibly be a solution to the problem 💡

**Comment by Daltimore** [comment]
Should we close this out now?

**Comment by tbm5k** [comment]
We could, but since have the backend is ready, I thought that you could implement the logic and finish up with the signup page

**Comment by tbm5k** [comment]
Yes, but could you also hope onto the other task so that you also work on the sign-up page?

**Comment by Daltimore** [comment]
Okay i will also do that and integrate the APIs respectively

**Comment by tbm5k** [comment]
Hey @Daltimore is there progress?
