### ISSUE TITLE
Repositioning and redesign of buttons

### ISSUE THREAD

**Issue by tbm5k** [mazarynxyz/mazaryn-frontend#15]

**Comment by tbm5k** [comment]
Hey @Afoxcute what's the progress?

**Comment by Afoxcute** [comment]
Working on it....discovered there is two css frameworks(materialui and antd). almost done with the search button.

**Comment by tbm5k** [comment]
Material is for the icons while ant is for the components

**Comment by tbm5k** [comment]
Hey @Afoxcute , how's the going?

**Comment by Afoxcute** [comment]
> Material is for the icons while ant is for the components

yes, I have got that.

**Comment by Afoxcute** [comment]
> Hey @Afoxcute , how's the going?

Sorry, Been busy working with the backend team concerning AWS.... I will get back soon.

**Comment by tbm5k** [comment]
okay,

**Comment by SouadAli10** [comment]
@tbm5k  please add a description for this task

**Comment by tbm5k** [comment]
@SouadAli10 run the app locally, then check on the figma, and do the changes, they are minute changes
