### ISSUE TITLE
profile page

### ISSUE THREAD

**Issue by tbm5k** [mazarynxyz/mazaryn-frontend#29]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/29680936/147752621-4c09e1c8-b931-47f2-bd73-20526494060e.png">
Create  :

- [x] profile photo
- [x] cover photo
- [ ] the buttons and make them functional 

> /friends/followers/
> /friends/following/
> /friends/all/

The posts and interests endpoints will be provided later on

**Comment by iamgabrielsoft** [comment]
am currently working on this right-away

**Comment by tbm5k** [comment]
@iamgabrielsoft ive updated the issue, kindly check on it
