### ISSUE TITLE
notifications page

### ISSUE THREAD

**Issue by tbm5k** [mazarynxyz/mazaryn-frontend#30]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/29680936/147913532-bbea18b8-d822-4b3d-8f8a-ae2ed14a6c29.png">

add the page above to the app. I'll link the API once the backend is up

**Comment by iamgabrielsoft** [comment]
I would work on it

**Comment by iamgabrielsoft** [comment]
Have fixed the Notification page
please close this issue😉
